### ISSUE TITLE
Update to version 0.16

### ISSUE THREAD

**Issue by jmigual** [smurph/Robocharger#3]
Thank you for your awesome work, do you think that you can update it to version 0.16?

**Comment by smurph** [comment]
hey, thanks for the kind words. 

I'm getting this updated now. Should be on mod portal, and a new release here soon.

**Comment by smurph** [comment]
[Mod portal updated](https://mods.factorio.com/mods/Smurph/Robocharger)

[Github release created](https://github.com/smurph/Robocharger/releases/tag/1.0.5)

This should work just fine. If you have any other issues, feel free to open a new one!
