### ISSUE TITLE
Construction Bot Attrition

### ISSUE THREAD

**Issue by Lepe0079** [smurph/Robocharger#5]
Construction Bots collide with each other and explode when a certain saturation level is reached. 
issue was found under the following conditions
-mostly vanilla server
-only other mods added were, far-reach, fill4me, even distribution, squeak through
-over 251 bots on a network of 4 roboports were active
-after each construction an amount of bots equal to the total - 251 were destroyed bringing the total back down to 251
this was replicated a total of 4 times.

-after mod was removed this issue was not replicated

**Comment by Lepe0079** [comment]
issue persisted at a lower rate hours after removal. issue must be somewhere else in the game install.

**Comment by smurph** [comment]
Yeah, this mod is simply a roboport with some changed configurations: 

- It's smaller in physical size and has a different sprite to account for that
- It can't hold repair packs or any bots of any type
- It allows for 10 bots to charge at once

This mod doesn't include any custom lua code or anything like that which would introduce new bot behavior
